#!/bin/sh

getent group apache || /usr/sbin/groupadd -g 48 apache
getent passwd apache || /usr/sbin/useradd -g apache -u 48 -d /var/www/htdocs -s /bin/false apache 2>/dev/null
/usr/bin/passwd -l apache

